// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwQRbO1ApneT2WAVVbyetYflJwlqgZQwI',
    appId: '1:287018129821:web:86eb8ba5ee9d3ae6d67774',
    messagingSenderId: '287018129821',
    projectId: 'food-delivery-app-aa4bc',
    authDomain: 'food-delivery-app-aa4bc.firebaseapp.com',
    storageBucket: 'food-delivery-app-aa4bc.appspot.com',
    measurementId: 'G-24S6D3B1H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS_AB-QV3Y55a0VcVEG7icmRgUPm5vPFM',
    appId: '1:287018129821:android:061393ec75ead807d67774',
    messagingSenderId: '287018129821',
    projectId: 'food-delivery-app-aa4bc',
    storageBucket: 'food-delivery-app-aa4bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWEU7r3bYGXOMsoXlJEjdZ7zexp_UxTHg',
    appId: '1:287018129821:ios:ac99e8c2a7baafaed67774',
    messagingSenderId: '287018129821',
    projectId: 'food-delivery-app-aa4bc',
    storageBucket: 'food-delivery-app-aa4bc.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWEU7r3bYGXOMsoXlJEjdZ7zexp_UxTHg',
    appId: '1:287018129821:ios:ac99e8c2a7baafaed67774',
    messagingSenderId: '287018129821',
    projectId: 'food-delivery-app-aa4bc',
    storageBucket: 'food-delivery-app-aa4bc.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwQRbO1ApneT2WAVVbyetYflJwlqgZQwI',
    appId: '1:287018129821:web:e5979dfebf2af6d1d67774',
    messagingSenderId: '287018129821',
    projectId: 'food-delivery-app-aa4bc',
    authDomain: 'food-delivery-app-aa4bc.firebaseapp.com',
    storageBucket: 'food-delivery-app-aa4bc.appspot.com',
    measurementId: 'G-E7ZQ51464M',
  );
}
